package com.example.examserviceone.vo.mclassgrade;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table m_class_grade
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MClassGrade implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   城市主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.city_id
     *
     * @mbg.generated
     */
    private Integer cityId;

    /**
     * Database Column Remarks:
     *   中心主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.org_id
     *
     * @mbg.generated
     */
    private Integer orgId;

    /**
     * Database Column Remarks:
     *   班号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.class_grade_code
     *
     * @mbg.generated
     */
    private String classGradeCode;

    /**
     * Database Column Remarks:
     *   班型主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.class_id
     *
     * @mbg.generated
     */
    private Integer classId;

    /**
     * Database Column Remarks:
     *   基础班型id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.base_class_id
     *
     * @mbg.generated
     */
    private Integer baseClassId;

    /**
     * Database Column Remarks:
     *   开班时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.start_date
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     * Database Column Remarks:
     *   节课时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.end_date
     *
     * @mbg.generated
     */
    private Date endDate;

    /**
     * Database Column Remarks:
     *   总课时数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.class_hours
     *
     * @mbg.generated
     */
    private Integer classHours;

    /**
     * Database Column Remarks:
     *   剩余课时数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.surplus_hours
     *
     * @mbg.generated
     */
    private BigDecimal surplusHours;

    /**
     * Database Column Remarks:
     *   班级状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.created_date
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     * Database Column Remarks:
     *   更新日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.updated_date
     *
     * @mbg.generated
     */
    private Date updatedDate;

    /**
     * Database Column Remarks:
     *   删除标志0-未删除，1-已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.delete_flag
     *
     * @mbg.generated
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.bms_id
     *
     * @mbg.generated
     */
    private String bmsId;

    /**
     * Database Column Remarks:
     *   接口标识：0-内部,1-接口,2-历史数据迁移
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.is_interface
     *
     * @mbg.generated
     */
    private Integer isInterface;

    /**
     * Database Column Remarks:
     *   复课标志:1-420复课,2-420复课rise+已停课
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.bmszj
     *
     * @mbg.generated
     */
    private String bmszj;

    /**
     * Database Column Remarks:
     *   上课周期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.weekday
     *
     * @mbg.generated
     */
    private String weekday;

    /**
     * Database Column Remarks:
     *   班级在读人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.student_num
     *
     * @mbg.generated
     */
    private Integer studentNum;

    /**
     * Database Column Remarks:
     *   课程安排
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.class_grade_schedule
     *
     * @mbg.generated
     */
    private String classGradeSchedule;

    /**
     * Database Column Remarks:
     *   COS班级状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.cos_clazz_status
     *
     * @mbg.generated
     */
    private Integer cosClazzStatus;

    /**
     * Database Column Remarks:
     *   关联原班级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.source_id
     *
     * @mbg.generated
     */
    private String sourceId;

    /**
     * Database Column Remarks:
     *   班级类型(新招/升学)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.class_type
     *
     * @mbg.generated
     */
    private Integer classType;

    /**
     * Database Column Remarks:
     *   预计开班时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.expect_start_date
     *
     * @mbg.generated
     */
    private Date expectStartDate;

    /**
     * Database Column Remarks:
     *   上课时间描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.class_schedule_desc
     *
     * @mbg.generated
     */
    private String classScheduleDesc;

    /**
     * Database Column Remarks:
     *   教师组合模式字典表 teacherMode 1. 主教/助教；2. 全科主教/学习规划师；3. 全科独立
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.teacher_mode
     *
     * @mbg.generated
     */
    private Integer teacherMode;

    /**
     * Database Column Remarks:
     *   主教、全科和全科独立
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.teacher_master
     *
     * @mbg.generated
     */
    private Integer teacherMaster;

    /**
     * Database Column Remarks:
     *   助教和规划师
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.teacher_assistant
     *
     * @mbg.generated
     */
    private Integer teacherAssistant;

    /**
     * Database Column Remarks:
     *   开学典礼时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.opening_ceremony_date
     *
     * @mbg.generated
     */
    private Date openingCeremonyDate;

    /**
     * Database Column Remarks:
     *   进入升学季月份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.year_month_entrance
     *
     * @mbg.generated
     */
    private Integer yearMonthEntrance;

    /**
     * Database Column Remarks:
     *   是否关闭 字典表yesorno
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.is_close
     *
     * @mbg.generated
     */
    private Integer isClose;

    /**
     * Database Column Remarks:
     *   关闭原因
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.reason_close
     *
     * @mbg.generated
     */
    private String reasonClose;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.comments
     *
     * @mbg.generated
     */
    private String comments;

    /**
     * Database Column Remarks:
     *   是否允许招生，字典表yesorno
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.allow_enroll_student
     *
     * @mbg.generated
     */
    private Integer allowEnrollStudent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.twelve_course_date
     *
     * @mbg.generated
     */
    private Date twelveCourseDate;

    /**
     * Database Column Remarks:
     *   原班型班号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.source_grade_codes
     *
     * @mbg.generated
     */
    private String sourceGradeCodes;

    /**
     * Database Column Remarks:
     *   原班型结课日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.source_end_dates
     *
     * @mbg.generated
     */
    private String sourceEndDates;

    /**
     * Database Column Remarks:
     *   第一个学员进班时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.first_student_enter_date
     *
     * @mbg.generated
     */
    private Date firstStudentEnterDate;

    /**
     * Database Column Remarks:
     *   颜色标识 1 红色，2 黄色, 3 没有色彩， 默认 3 ; 适用 校区开班计划查询
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.row_color
     *
     * @mbg.generated
     */
    private Integer rowColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.class_room_schedule
     *
     * @mbg.generated
     */
    private String classRoomSchedule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.class_teacher_schedule
     *
     * @mbg.generated
     */
    private String classTeacherSchedule;

    /**
     * Database Column Remarks:
     *   品牌ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.brand_id
     *
     * @mbg.generated
     */
    private Integer brandId;

    /**
     * Database Column Remarks:
     *   一次课程时长，默认分钟
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.duration
     *
     * @mbg.generated
     */
    private Integer duration;

    /**
     * Database Column Remarks:
     *   上课方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.teach_way
     *
     * @mbg.generated
     */
    private Integer teachWay;

    /**
     * Database Column Remarks:
     *   班主任，填写employee_id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.head_master
     *
     * @mbg.generated
     */
    private String headMaster;

    /**
     * Database Column Remarks:
     *   线上课每堂课时长，默认分钟
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.online_duration
     *
     * @mbg.generated
     */
    private Integer onlineDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.workday_hours
     *
     * @mbg.generated
     */
    private BigDecimal workdayHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.weekend_hours
     *
     * @mbg.generated
     */
    private BigDecimal weekendHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_class_grade.teacher_desc
     *
     * @mbg.generated
     */
    private String teacherDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_class_grade
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.id
     *
     * @return the value of m_class_grade.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.id
     *
     * @param id the value for m_class_grade.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.city_id
     *
     * @return the value of m_class_grade.city_id
     *
     * @mbg.generated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.city_id
     *
     * @param cityId the value for m_class_grade.city_id
     *
     * @mbg.generated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.org_id
     *
     * @return the value of m_class_grade.org_id
     *
     * @mbg.generated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.org_id
     *
     * @param orgId the value for m_class_grade.org_id
     *
     * @mbg.generated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.class_grade_code
     *
     * @return the value of m_class_grade.class_grade_code
     *
     * @mbg.generated
     */
    public String getClassGradeCode() {
        return classGradeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.class_grade_code
     *
     * @param classGradeCode the value for m_class_grade.class_grade_code
     *
     * @mbg.generated
     */
    public void setClassGradeCode(String classGradeCode) {
        this.classGradeCode = classGradeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.class_id
     *
     * @return the value of m_class_grade.class_id
     *
     * @mbg.generated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.class_id
     *
     * @param classId the value for m_class_grade.class_id
     *
     * @mbg.generated
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.base_class_id
     *
     * @return the value of m_class_grade.base_class_id
     *
     * @mbg.generated
     */
    public Integer getBaseClassId() {
        return baseClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.base_class_id
     *
     * @param baseClassId the value for m_class_grade.base_class_id
     *
     * @mbg.generated
     */
    public void setBaseClassId(Integer baseClassId) {
        this.baseClassId = baseClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.start_date
     *
     * @return the value of m_class_grade.start_date
     *
     * @mbg.generated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.start_date
     *
     * @param startDate the value for m_class_grade.start_date
     *
     * @mbg.generated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.end_date
     *
     * @return the value of m_class_grade.end_date
     *
     * @mbg.generated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.end_date
     *
     * @param endDate the value for m_class_grade.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.class_hours
     *
     * @return the value of m_class_grade.class_hours
     *
     * @mbg.generated
     */
    public Integer getClassHours() {
        return classHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.class_hours
     *
     * @param classHours the value for m_class_grade.class_hours
     *
     * @mbg.generated
     */
    public void setClassHours(Integer classHours) {
        this.classHours = classHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.surplus_hours
     *
     * @return the value of m_class_grade.surplus_hours
     *
     * @mbg.generated
     */
    public BigDecimal getSurplusHours() {
        return surplusHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.surplus_hours
     *
     * @param surplusHours the value for m_class_grade.surplus_hours
     *
     * @mbg.generated
     */
    public void setSurplusHours(BigDecimal surplusHours) {
        this.surplusHours = surplusHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.status
     *
     * @return the value of m_class_grade.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.status
     *
     * @param status the value for m_class_grade.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.created_by
     *
     * @return the value of m_class_grade.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.created_by
     *
     * @param createdBy the value for m_class_grade.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.created_date
     *
     * @return the value of m_class_grade.created_date
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.created_date
     *
     * @param createdDate the value for m_class_grade.created_date
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.updated_by
     *
     * @return the value of m_class_grade.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.updated_by
     *
     * @param updatedBy the value for m_class_grade.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.updated_date
     *
     * @return the value of m_class_grade.updated_date
     *
     * @mbg.generated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.updated_date
     *
     * @param updatedDate the value for m_class_grade.updated_date
     *
     * @mbg.generated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.delete_flag
     *
     * @return the value of m_class_grade.delete_flag
     *
     * @mbg.generated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.delete_flag
     *
     * @param deleteFlag the value for m_class_grade.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.bms_id
     *
     * @return the value of m_class_grade.bms_id
     *
     * @mbg.generated
     */
    public String getBmsId() {
        return bmsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.bms_id
     *
     * @param bmsId the value for m_class_grade.bms_id
     *
     * @mbg.generated
     */
    public void setBmsId(String bmsId) {
        this.bmsId = bmsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.is_interface
     *
     * @return the value of m_class_grade.is_interface
     *
     * @mbg.generated
     */
    public Integer getIsInterface() {
        return isInterface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.is_interface
     *
     * @param isInterface the value for m_class_grade.is_interface
     *
     * @mbg.generated
     */
    public void setIsInterface(Integer isInterface) {
        this.isInterface = isInterface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.bmszj
     *
     * @return the value of m_class_grade.bmszj
     *
     * @mbg.generated
     */
    public String getBmszj() {
        return bmszj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.bmszj
     *
     * @param bmszj the value for m_class_grade.bmszj
     *
     * @mbg.generated
     */
    public void setBmszj(String bmszj) {
        this.bmszj = bmszj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.weekday
     *
     * @return the value of m_class_grade.weekday
     *
     * @mbg.generated
     */
    public String getWeekday() {
        return weekday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.weekday
     *
     * @param weekday the value for m_class_grade.weekday
     *
     * @mbg.generated
     */
    public void setWeekday(String weekday) {
        this.weekday = weekday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.student_num
     *
     * @return the value of m_class_grade.student_num
     *
     * @mbg.generated
     */
    public Integer getStudentNum() {
        return studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.student_num
     *
     * @param studentNum the value for m_class_grade.student_num
     *
     * @mbg.generated
     */
    public void setStudentNum(Integer studentNum) {
        this.studentNum = studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.class_grade_schedule
     *
     * @return the value of m_class_grade.class_grade_schedule
     *
     * @mbg.generated
     */
    public String getClassGradeSchedule() {
        return classGradeSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.class_grade_schedule
     *
     * @param classGradeSchedule the value for m_class_grade.class_grade_schedule
     *
     * @mbg.generated
     */
    public void setClassGradeSchedule(String classGradeSchedule) {
        this.classGradeSchedule = classGradeSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.cos_clazz_status
     *
     * @return the value of m_class_grade.cos_clazz_status
     *
     * @mbg.generated
     */
    public Integer getCosClazzStatus() {
        return cosClazzStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.cos_clazz_status
     *
     * @param cosClazzStatus the value for m_class_grade.cos_clazz_status
     *
     * @mbg.generated
     */
    public void setCosClazzStatus(Integer cosClazzStatus) {
        this.cosClazzStatus = cosClazzStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.source_id
     *
     * @return the value of m_class_grade.source_id
     *
     * @mbg.generated
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.source_id
     *
     * @param sourceId the value for m_class_grade.source_id
     *
     * @mbg.generated
     */
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.class_type
     *
     * @return the value of m_class_grade.class_type
     *
     * @mbg.generated
     */
    public Integer getClassType() {
        return classType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.class_type
     *
     * @param classType the value for m_class_grade.class_type
     *
     * @mbg.generated
     */
    public void setClassType(Integer classType) {
        this.classType = classType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.expect_start_date
     *
     * @return the value of m_class_grade.expect_start_date
     *
     * @mbg.generated
     */
    public Date getExpectStartDate() {
        return expectStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.expect_start_date
     *
     * @param expectStartDate the value for m_class_grade.expect_start_date
     *
     * @mbg.generated
     */
    public void setExpectStartDate(Date expectStartDate) {
        this.expectStartDate = expectStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.class_schedule_desc
     *
     * @return the value of m_class_grade.class_schedule_desc
     *
     * @mbg.generated
     */
    public String getClassScheduleDesc() {
        return classScheduleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.class_schedule_desc
     *
     * @param classScheduleDesc the value for m_class_grade.class_schedule_desc
     *
     * @mbg.generated
     */
    public void setClassScheduleDesc(String classScheduleDesc) {
        this.classScheduleDesc = classScheduleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.teacher_mode
     *
     * @return the value of m_class_grade.teacher_mode
     *
     * @mbg.generated
     */
    public Integer getTeacherMode() {
        return teacherMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.teacher_mode
     *
     * @param teacherMode the value for m_class_grade.teacher_mode
     *
     * @mbg.generated
     */
    public void setTeacherMode(Integer teacherMode) {
        this.teacherMode = teacherMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.teacher_master
     *
     * @return the value of m_class_grade.teacher_master
     *
     * @mbg.generated
     */
    public Integer getTeacherMaster() {
        return teacherMaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.teacher_master
     *
     * @param teacherMaster the value for m_class_grade.teacher_master
     *
     * @mbg.generated
     */
    public void setTeacherMaster(Integer teacherMaster) {
        this.teacherMaster = teacherMaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.teacher_assistant
     *
     * @return the value of m_class_grade.teacher_assistant
     *
     * @mbg.generated
     */
    public Integer getTeacherAssistant() {
        return teacherAssistant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.teacher_assistant
     *
     * @param teacherAssistant the value for m_class_grade.teacher_assistant
     *
     * @mbg.generated
     */
    public void setTeacherAssistant(Integer teacherAssistant) {
        this.teacherAssistant = teacherAssistant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.opening_ceremony_date
     *
     * @return the value of m_class_grade.opening_ceremony_date
     *
     * @mbg.generated
     */
    public Date getOpeningCeremonyDate() {
        return openingCeremonyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.opening_ceremony_date
     *
     * @param openingCeremonyDate the value for m_class_grade.opening_ceremony_date
     *
     * @mbg.generated
     */
    public void setOpeningCeremonyDate(Date openingCeremonyDate) {
        this.openingCeremonyDate = openingCeremonyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.year_month_entrance
     *
     * @return the value of m_class_grade.year_month_entrance
     *
     * @mbg.generated
     */
    public Integer getYearMonthEntrance() {
        return yearMonthEntrance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.year_month_entrance
     *
     * @param yearMonthEntrance the value for m_class_grade.year_month_entrance
     *
     * @mbg.generated
     */
    public void setYearMonthEntrance(Integer yearMonthEntrance) {
        this.yearMonthEntrance = yearMonthEntrance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.is_close
     *
     * @return the value of m_class_grade.is_close
     *
     * @mbg.generated
     */
    public Integer getIsClose() {
        return isClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.is_close
     *
     * @param isClose the value for m_class_grade.is_close
     *
     * @mbg.generated
     */
    public void setIsClose(Integer isClose) {
        this.isClose = isClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.reason_close
     *
     * @return the value of m_class_grade.reason_close
     *
     * @mbg.generated
     */
    public String getReasonClose() {
        return reasonClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.reason_close
     *
     * @param reasonClose the value for m_class_grade.reason_close
     *
     * @mbg.generated
     */
    public void setReasonClose(String reasonClose) {
        this.reasonClose = reasonClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.comments
     *
     * @return the value of m_class_grade.comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.comments
     *
     * @param comments the value for m_class_grade.comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.allow_enroll_student
     *
     * @return the value of m_class_grade.allow_enroll_student
     *
     * @mbg.generated
     */
    public Integer getAllowEnrollStudent() {
        return allowEnrollStudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.allow_enroll_student
     *
     * @param allowEnrollStudent the value for m_class_grade.allow_enroll_student
     *
     * @mbg.generated
     */
    public void setAllowEnrollStudent(Integer allowEnrollStudent) {
        this.allowEnrollStudent = allowEnrollStudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.twelve_course_date
     *
     * @return the value of m_class_grade.twelve_course_date
     *
     * @mbg.generated
     */
    public Date getTwelveCourseDate() {
        return twelveCourseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.twelve_course_date
     *
     * @param twelveCourseDate the value for m_class_grade.twelve_course_date
     *
     * @mbg.generated
     */
    public void setTwelveCourseDate(Date twelveCourseDate) {
        this.twelveCourseDate = twelveCourseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.source_grade_codes
     *
     * @return the value of m_class_grade.source_grade_codes
     *
     * @mbg.generated
     */
    public String getSourceGradeCodes() {
        return sourceGradeCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.source_grade_codes
     *
     * @param sourceGradeCodes the value for m_class_grade.source_grade_codes
     *
     * @mbg.generated
     */
    public void setSourceGradeCodes(String sourceGradeCodes) {
        this.sourceGradeCodes = sourceGradeCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.source_end_dates
     *
     * @return the value of m_class_grade.source_end_dates
     *
     * @mbg.generated
     */
    public String getSourceEndDates() {
        return sourceEndDates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.source_end_dates
     *
     * @param sourceEndDates the value for m_class_grade.source_end_dates
     *
     * @mbg.generated
     */
    public void setSourceEndDates(String sourceEndDates) {
        this.sourceEndDates = sourceEndDates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.first_student_enter_date
     *
     * @return the value of m_class_grade.first_student_enter_date
     *
     * @mbg.generated
     */
    public Date getFirstStudentEnterDate() {
        return firstStudentEnterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.first_student_enter_date
     *
     * @param firstStudentEnterDate the value for m_class_grade.first_student_enter_date
     *
     * @mbg.generated
     */
    public void setFirstStudentEnterDate(Date firstStudentEnterDate) {
        this.firstStudentEnterDate = firstStudentEnterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.row_color
     *
     * @return the value of m_class_grade.row_color
     *
     * @mbg.generated
     */
    public Integer getRowColor() {
        return rowColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.row_color
     *
     * @param rowColor the value for m_class_grade.row_color
     *
     * @mbg.generated
     */
    public void setRowColor(Integer rowColor) {
        this.rowColor = rowColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.class_room_schedule
     *
     * @return the value of m_class_grade.class_room_schedule
     *
     * @mbg.generated
     */
    public String getClassRoomSchedule() {
        return classRoomSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.class_room_schedule
     *
     * @param classRoomSchedule the value for m_class_grade.class_room_schedule
     *
     * @mbg.generated
     */
    public void setClassRoomSchedule(String classRoomSchedule) {
        this.classRoomSchedule = classRoomSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.class_teacher_schedule
     *
     * @return the value of m_class_grade.class_teacher_schedule
     *
     * @mbg.generated
     */
    public String getClassTeacherSchedule() {
        return classTeacherSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.class_teacher_schedule
     *
     * @param classTeacherSchedule the value for m_class_grade.class_teacher_schedule
     *
     * @mbg.generated
     */
    public void setClassTeacherSchedule(String classTeacherSchedule) {
        this.classTeacherSchedule = classTeacherSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.brand_id
     *
     * @return the value of m_class_grade.brand_id
     *
     * @mbg.generated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.brand_id
     *
     * @param brandId the value for m_class_grade.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.duration
     *
     * @return the value of m_class_grade.duration
     *
     * @mbg.generated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.duration
     *
     * @param duration the value for m_class_grade.duration
     *
     * @mbg.generated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.teach_way
     *
     * @return the value of m_class_grade.teach_way
     *
     * @mbg.generated
     */
    public Integer getTeachWay() {
        return teachWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.teach_way
     *
     * @param teachWay the value for m_class_grade.teach_way
     *
     * @mbg.generated
     */
    public void setTeachWay(Integer teachWay) {
        this.teachWay = teachWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.head_master
     *
     * @return the value of m_class_grade.head_master
     *
     * @mbg.generated
     */
    public String getHeadMaster() {
        return headMaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.head_master
     *
     * @param headMaster the value for m_class_grade.head_master
     *
     * @mbg.generated
     */
    public void setHeadMaster(String headMaster) {
        this.headMaster = headMaster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.online_duration
     *
     * @return the value of m_class_grade.online_duration
     *
     * @mbg.generated
     */
    public Integer getOnlineDuration() {
        return onlineDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.online_duration
     *
     * @param onlineDuration the value for m_class_grade.online_duration
     *
     * @mbg.generated
     */
    public void setOnlineDuration(Integer onlineDuration) {
        this.onlineDuration = onlineDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.workday_hours
     *
     * @return the value of m_class_grade.workday_hours
     *
     * @mbg.generated
     */
    public BigDecimal getWorkdayHours() {
        return workdayHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.workday_hours
     *
     * @param workdayHours the value for m_class_grade.workday_hours
     *
     * @mbg.generated
     */
    public void setWorkdayHours(BigDecimal workdayHours) {
        this.workdayHours = workdayHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.weekend_hours
     *
     * @return the value of m_class_grade.weekend_hours
     *
     * @mbg.generated
     */
    public BigDecimal getWeekendHours() {
        return weekendHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.weekend_hours
     *
     * @param weekendHours the value for m_class_grade.weekend_hours
     *
     * @mbg.generated
     */
    public void setWeekendHours(BigDecimal weekendHours) {
        this.weekendHours = weekendHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_class_grade.teacher_desc
     *
     * @return the value of m_class_grade.teacher_desc
     *
     * @mbg.generated
     */
    public String getTeacherDesc() {
        return teacherDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_class_grade.teacher_desc
     *
     * @param teacherDesc the value for m_class_grade.teacher_desc
     *
     * @mbg.generated
     */
    public void setTeacherDesc(String teacherDesc) {
        this.teacherDesc = teacherDesc;
    }
}