package com.example.teach.mapper;

import com.example.teach.entity.MClassGrade;
import com.example.teach.entity.MClassGradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MClassGradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_class_grade
     *
     * @mbg.generated
     */
    long countByExample(MClassGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_class_grade
     *
     * @mbg.generated
     */
    int deleteByExample(MClassGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_class_grade
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_class_grade
     *
     * @mbg.generated
     */
    int insert(MClassGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_class_grade
     *
     * @mbg.generated
     */
    int insertSelective(MClassGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_class_grade
     *
     * @mbg.generated
     */
    List<MClassGrade> selectByExample(MClassGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_class_grade
     *
     * @mbg.generated
     */
    MClassGrade selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_class_grade
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MClassGrade record, @Param("example") MClassGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_class_grade
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MClassGrade record, @Param("example") MClassGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_class_grade
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MClassGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_class_grade
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MClassGrade record);
}